//// AUTH
export const LOGIN = "AUTH/LOGIN";
export const LOGOUT = "AUTH/LOGOUT";
export const ERROR = "AUTH/ERROR";
//// APP
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SHOW_FULL_ALERT = "APP/SHOW_FULL_ALERT";
export const HIDE_FULL_ALERT = "APP/HIDE_FULL_ALERT";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
export const GET_NOTIFICATIONS = "APP/GET_NOTIFICATIONS";
//// ORDER
export const CREATE_ORDER = "ORDER/CREATE_ORDER";
export const UPDATE_ORDER = "ORDER/UPDATE_ORDER";
export const GET_TASKS = "ORDER/GET_TASKS";
export const GET_SPEC = "ORDER/GET_SPEC";
export const GET_SUB_SPEC = "ORDER/GET_SUB_SPEC";
export const GET_ORDERS = "ORDER/GET_ORDERS";
export const GET_COUNT = "ORDER/GET_COUNT";
export const GET_ORDER = "ORDER/GET_ORDER";
export const TAKE_IN_WORK = "ORDER/TAKE_IN_WORK";
export const CANCEL_ORDER = "ORDER/CANCEL_ORDER";
export const DONE_ORDER = "ORDER/DONE_ORDER";
export const ADD_COMMENT = "ORDER/ADD_COMMENT";
export const GET_COMMENT = "ORDER/GET_COMMENT";
export const DELETE_ORDER = "ORDER/DELETE_ORDER";
//// ORDER_FILTER
export const GET_F_SPEC = "ORDER_FILTER/GET_F_SPEC";
export const GET_F_SUB_SPEC = "ORDER_FILTER/GET_F_SUB_SPEC";
export const GET_F_EXECUTOR = "ORDER_FILTER/GET_F_EXECUTOR";
export const GET_F_STATUS = "ORDER_FILTER/GET_F_STATUS";
//// DASHBOARD
export const GET_DASHBOARD_DATA = "DASHBOARD/GET_DASHBOARD_DATA";
//// PROFILE
export const GET_GENERAL_SETTINGS = "PROFILE/GET_GENERAL_SETTINGS";
export const GET_USER_IMG = "PROFILE/GET_USER_IMG";
export const CHANGE_GENERAL_SETTINGS = "PROFILE/CHANGE_GENERAL_SETTINGS";
export const CHANGE_AVATAR = "PROFILE/CHANGE_AVATAR";
export const CHANGE_PASSWORD = "PROFILE/CHANGE_PASSWORD";
export const GET_USER_NOTIFICATIONS = "PROFILE/GET_USER_NOTIFICATIONS";
export const GET_NOTIFICATIONS_SETTINGS = "PROFILE/GET_NOTIFICATIONS_SETTINGS";
export const CHANGE_NOTIFICATIONS = "PROFILE/CHANGE_NOTIFICATIONS";
export const GET_USER_TELEGRAM = "PROFILE/GET_USER_TELEGRAM";
